name: Tests

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { python: '3.6', os: ubuntu-latest }
          - { python: '3.7', os: ubuntu-latest }
          - { python: '3.8', os: ubuntu-latest }
          - { python: '3.9', os: ubuntu-latest }
          - { python: '3.7', os: windows-latest }
          - { python: '3.7', os: macos-latest }

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel pytest
      - name: Install
        run: |
          python setup.py install
      - name: Test with pytest
        run: |
          pytest tests